/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Registry } from './Registry.js';
export * as factories from './factories/index.js';
export { Registry__factory } from './factories/Registry__factory.js';