/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface RegistryInterface extends Interface {
    getFunction(nameOrSignature: "anchor" | "records" | "verify"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Anchored"): EventFragment;

    encodeFunctionData(functionFragment: 'anchor', values: [BytesLike, string]): string;
encodeFunctionData(functionFragment: 'records', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'verify', values: [BytesLike]): string;

    decodeFunctionResult(functionFragment: 'anchor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'records', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verify', data: BytesLike): Result;
  }

  
    export namespace AnchoredEvent {
      export type InputTuple = [fingerprint: BytesLike, submitter: AddressLike, timestamp: BigNumberish, uri: string];
      export type OutputTuple = [fingerprint: string, submitter: string, timestamp: bigint, uri: string];
      export interface OutputObject {fingerprint: string, submitter: string, timestamp: bigint, uri: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Registry extends BaseContract {
    
    connect(runner?: ContractRunner | null): Registry;
    waitForDeployment(): Promise<this>;

    interface: RegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    anchor: TypedContractMethod<
      [fingerprint: BytesLike, uri: string, ],
      [void],
      'nonpayable'
    >
    

    
    records: TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, bigint, string] & {submitter: string, timestamp: bigint, uri: string }],
      'view'
    >
    

    
    verify: TypedContractMethod<
      [fingerprint: BytesLike, ],
      [[boolean, string, bigint, string] & {exists: boolean, submitter: string, timestamp: bigint, uri: string }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'anchor'): TypedContractMethod<
      [fingerprint: BytesLike, uri: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'records'): TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, bigint, string] & {submitter: string, timestamp: bigint, uri: string }],
      'view'
    >;
getFunction(nameOrSignature: 'verify'): TypedContractMethod<
      [fingerprint: BytesLike, ],
      [[boolean, string, bigint, string] & {exists: boolean, submitter: string, timestamp: bigint, uri: string }],
      'view'
    >;

    getEvent(key: 'Anchored'): TypedContractEvent<AnchoredEvent.InputTuple, AnchoredEvent.OutputTuple, AnchoredEvent.OutputObject>;

    filters: {
      
      'Anchored(bytes32,address,uint64,string)': TypedContractEvent<AnchoredEvent.InputTuple, AnchoredEvent.OutputTuple, AnchoredEvent.OutputObject>;
      Anchored: TypedContractEvent<AnchoredEvent.InputTuple, AnchoredEvent.OutputTuple, AnchoredEvent.OutputObject>;
    
    };
  }